### ISSUE TITLE
Save the country configuration

### ISSUE THREAD

**Issue by ldasilva-net** [SubhamTyagi/openinwa#14]
Hi, first at all, thanks for the app!
The majority of the contacts usually are from your country. I think is a good idea save the country to the preference when I select one. So when I reopen the app, get as default the last country what I choose.

**Comment by IronShing** [comment]
I second this.

**Comment by iamtalhaasghar** [comment]
The app saves and sets the country automatically to the last opened number's country.

For example: if you opened a US number last time then the next time you open the app, you will see US selected.
After that if you enter a  Canadian number next time you will see Canada selected.

Its obvious if you open your contacts then you will don't have to worry to change country again and again.

**Comment by SubhamTyagi** [comment]
Alredy fixed
