### ISSUE TITLE
allow to paste anything

### ISSUE THREAD

**Issue by utack** [SubhamTyagi/openinwa#2]
Currently the app seems to check if a number or string makes sense, when pasted.  
I use this app to chat with foreign numbers that I 90% of the time copy from websites.  
There can be an additional "+44" or an additional "0" in the beginning that gets copied as well, I would prefer to paste it either way, and then fix it once it is pasted.  
However right now this does not work, i have to either paste it elsewhere to fix the format first or move around the copy-cursors to be precise before copying.  
Could you please consider removing any paste-checks?

**Comment by SubhamTyagi** [comment]
Hi @utack,
I have pushed latest version to github and latest version(1.2) will be available in F-droid in few days. if you want to download apk you can find it in release section
