### ISSUE TITLE
https?

### ISSUE THREAD

**Issue by alanthehat** [SubhamTyagi/openinwa#20]
This app produces an unsecured **http** link, should it be secured with **https**?
> http://api.whatsapp.com/send?phone=<a number\>&text=<text\> 

vs 
> https://api.whatsapp.com/send?phone=<a number\>&text=<text\>

**Comment by federicomassi** [comment]
It should be better to use https:// , since the WA app seems to use it from years.

Maybe it should be better to use an option to grant both the possibilities?

**Comment by SubhamTyagi** [comment]
This is only fancy.  These links are only used for 'Intent'(a android thing)  Which is intercepted by whatsapp app and then these URLs are parsed by whatsapp app.  This app doesn't make any intenet connection to whatsapp server moreover this app doesn't have any internet permission (check android manifest file) so this app cannot access internet.

**Comment by Herisanto** [comment]
Bagaimana cara mengunakan aplikasi ini mohon tutorialnya

**Comment by SubhamTyagi** [comment]
fixed
