### ISSUE TITLE
Kuwait has added numbers starting from 4

### ISSUE THREAD

**Issue by IronShing** [SubhamTyagi/openinwa#28]
It doesn't even try to look for numbers starting from 4.

**Comment by SubhamTyagi** [comment]
Could you elaborate your issue using some examples numbers.

**Comment by IronShing** [comment]
![Screenshot_20240623_103656_Open In WhatsApp](https://github.com/SubhamTyagi/openinwa/assets/56222393/faba5394-1451-476b-831a-7dbe42481f5e)

**Comment by IronShing** [comment]
I'm so happy to see an update to the app. 

I was expecting this issue would have been solved. 

I'm adding am example you can't add this number from the app
 
![Screenshot_20240718_190457_WhatsApp](https://github.com/user-attachments/assets/f02d2c07-1027-466e-9022-bc6da3748573)

**Comment by SubhamTyagi** [comment]
fixed in v1.5

**Comment by IronShing** [comment]
Can't try it yet but thanks

**Comment by SubhamTyagi** [comment]
Will be available on F-droid as soon as fdroid build cycle pickup this version.
Btw you can download the apk from 

https://github.com/SubhamTyagi/openinwa/actions/runs/10021401937

But you have to uninstall the previous installed apk
