### ISSUE TITLE
Phonenumbers not visible

### ISSUE THREAD

**Issue by morty303** [SubhamTyagi/openinwa#29]
Phone numbers are not visible in Dark Mode after Update to Version 1.4 (7).
Black text on a black background.
Hope you can fix this.

Best Regards

**Comment by Lanchon** [comment]
i am also affected by this issue.

**Comment by IronShing** [comment]
She

**Comment by SubhamTyagi** [comment]
fixed in v1.5

**Comment by Lanchon** [comment]
confirmed fixed, please close issue

thanks,!
